process.stdout.write('hello node!' + '\n');
console.log(process.argv);
console.log('---');
console.log(process.env);
console.log('---');
console.log(process.installPrefix);
console.log('---');
console.log(process.pid);
console.log('---');
console.log(process.platform);
console.log('---');
console.log(process.title);
console.log('---');
console.log(process.version);
